<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <LangVersion>Latest</LangVersion>
        <Authors>Koki</Authors>
        <Version>1.0.0</Version>

        <RestoreAdditionalProjectSources>
            https://api.nuget.org/v3/index.json;
            https://nuget.bepinex.dev/v3/index.json;
            https://nuget.windows10ce.com/nuget/v3/index.json
        </RestoreAdditionalProjectSources>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all" />
        <PackageReference Include="BepInEx.Core" Version="5.*" ExcludeAssets="runtime" />
        <PackageReference Include="UnityEngine.Modules" Version="2021.3.45" IncludeAssets="compile" PrivateAssets="all" />
        <PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" Version="0.4.1" PrivateAssets="all" IncludeAssets="build" />
    </ItemGroup>

    
    <PropertyGroup>
        <IncludeSymbols>true</IncludeSymbols>
        <DebugSymbols>true</DebugSymbols>
        <DebugType>embedded</DebugType>

        <DLLs>D:\SteamLibrary\steamapps\common\STRAFTAT\STRAFTAT_Data\Managed</DLLs>
        <BepInExPlugins>C:\Users\koki\AppData\Roaming\com.kesomannen.gale\straftat\profiles\Default\BepInEx\plugins</BepInExPlugins>
    </PropertyGroup>

    <ItemGroup>
        <Reference Include="Assembly-CSharp" Publicize="true">
            <HintPath>$(DLLs)\Assembly-CSharp.dll</HintPath>
        </Reference>
        <Reference Include="ComputerysModdingUtilities">
            <HintPath>$(DLLs)\ComputerysModdingUtilities.dll</HintPath>
        </Reference>
        <Reference Include="TextMeshProUGUI">
            <HintPath>$(DLLs)\TextMeshProUGUI.dll</HintPath>
        </Reference>
    </ItemGroup>

    <Target Name="CopyDLL" AfterTargets="Build">
        <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(BepInExPlugins)\StraftTweaks" />
    </Target>
</Project>